// Generated by tools/gen_font.py. Do not hand-edit.
#pragma once
namespace lens {
// 96 printable ASCII glyphs, 8 rows each, 6 columns wide, bit 5 = leftmost.
extern const unsigned char kGlyphRows[96][8];
}  // namespace lens
